---
name: Prerelease
on:
  push:
    tags:
      # alpha and beta only, and ignore wowinterface since it doesn't support alpha/beta releases
      - "**-alpha**"
      - "**-beta**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checkout the project
      - uses: actions/checkout@v4
        with:
          submodules: recursive,
          fetch-depth: 0

        #use the bigwigs packager
      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_KEY }}
